# permissions for end users to view ubans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uban-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-crd
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
  name: uban-viewer-role
rules:
- apiGroups:
  - saleh.dev.saleh.dev
  resources:
  - ubans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saleh.dev.saleh.dev
  resources:
  - ubans/status
  verbs:
  - get
